// <auto-generated />
using System;
using Labb1___LINQ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1___LINQ.Migrations
{
    [DbContext(typeof(E_CommerceContext))]
    [Migration("20250416133254_newChanges")]
    partial class newChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb1___LINQ.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Elektronik och tekniska produkter",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Produkter för hemmet och köket",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Kläder och accessoarer",
                            Name = "CLothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Sportutrustning och träningsprodukter",
                            Name = "Sports"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Böcker och litteratur",
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Adress = "Storgatan 1, Stockholm",
                            Email = "anders@example.com",
                            Name = "Anders Svensson",
                            Phone = -2274
                        },
                        new
                        {
                            CustomerId = 2,
                            Adress = "Kungsgatan 15, Göteborg",
                            Email = "emma@example.com",
                            Name = "Emma johansson",
                            Phone = -3493
                        },
                        new
                        {
                            CustomerId = 3,
                            Adress = "Drottninggatan 8, Malmö",
                            Email = "lars@example.com",
                            Name = "Lars Nilsson",
                            Phone = -4712
                        },
                        new
                        {
                            CustomerId = 4,
                            Adress = "Sveavägen 22, Uppsala",
                            Email = "sofia@example.com",
                            Name = "Sofia Lindgren",
                            Phone = -5938
                        },
                        new
                        {
                            CustomerId = 5,
                            Adress = "Järntorget 5, Göteborg",
                            Email = "peter@example.com",
                            Name = "Peter Karlsson",
                            Phone = -7162
                        });
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalAmount = 11999
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalAmount = 9798
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalAmount = 18999
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 4,
                            OrderDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalAmount = 3499
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalAmount = 16994
                        },
                        new
                        {
                            OrderId = 6,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalAmount = 899
                        },
                        new
                        {
                            OrderId = 7,
                            CustomerId = 3,
                            OrderDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalAmount = 2498
                        },
                        new
                        {
                            OrderId = 8,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalAmount = 1598
                        },
                        new
                        {
                            OrderId = 9,
                            CustomerId = 4,
                            OrderDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalAmount = 5794
                        },
                        new
                        {
                            OrderId = 10,
                            CustomerId = 5,
                            OrderDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalAmount = 1299
                        });
                });

            modelBuilder.Entity("Labb1___LINQ.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 11999m
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 2,
                            UnitPrice = 3499m
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 2,
                            ProductId = 13,
                            Quantity = 2,
                            UnitPrice = 899m
                        },
                        new
                        {
                            OrderDetailId = 4,
                            OrderId = 3,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 18999m
                        },
                        new
                        {
                            OrderDetailId = 5,
                            OrderId = 4,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 3499m
                        },
                        new
                        {
                            OrderDetailId = 6,
                            OrderId = 5,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 12499m
                        },
                        new
                        {
                            OrderDetailId = 7,
                            OrderId = 5,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 4495m
                        },
                        new
                        {
                            OrderDetailId = 8,
                            OrderId = 6,
                            ProductId = 13,
                            Quantity = 1,
                            UnitPrice = 899m
                        },
                        new
                        {
                            OrderDetailId = 9,
                            OrderId = 7,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 1499m
                        },
                        new
                        {
                            OrderDetailId = 10,
                            OrderId = 7,
                            ProductId = 9,
                            Quantity = 3,
                            UnitPrice = 349m
                        },
                        new
                        {
                            OrderDetailId = 11,
                            OrderId = 8,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 1999m
                        },
                        new
                        {
                            OrderDetailId = 12,
                            OrderId = 8,
                            ProductId = 15,
                            Quantity = 3,
                            UnitPrice = 499m
                        },
                        new
                        {
                            OrderDetailId = 13,
                            OrderId = 9,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 8999m
                        },
                        new
                        {
                            OrderDetailId = 14,
                            OrderId = 9,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 1299m
                        },
                        new
                        {
                            OrderDetailId = 15,
                            OrderId = 9,
                            ProductId = 14,
                            Quantity = 2,
                            UnitPrice = 799m
                        },
                        new
                        {
                            OrderDetailId = 16,
                            OrderId = 10,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 1299m
                        });
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Smartphone med 128GB lagring",
                            Name = "iPhone 13 Pro",
                            Price = 11999m,
                            StockQuantity = 15,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = " 4K Smart TV med HDR",
                            Name = "Samsung TV 55\"",
                            Price = 11999m,
                            StockQuantity = 15,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Trådlösa hörlurar med brusreducering",
                            Name = "Sony WH-1000XM4",
                            Price = 8999m,
                            StockQuantity = 8,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "Laptop med M1-chip och 8GB RAM",
                            Name = "MacBook Air",
                            Price = 3499m,
                            StockQuantity = 7,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Automatisk espressomaskin",
                            Name = "Espressomaskin",
                            Price = 12499m,
                            StockQuantity = 12,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Multifunktionell köksmaskin",
                            Name = "Matberedare",
                            Price = 1299m,
                            StockQuantity = 20,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Varm jacka för vinterbruk",
                            Name = "Vinteracka",
                            Price = 1999m,
                            StockQuantity = 25,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "Skor för distanslöpning",
                            Name = "Löparskor",
                            Price = 1499m,
                            StockQuantity = 18,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Description = "Halkfri yogamatta",
                            Name = "Yogamatta",
                            Price = 349m,
                            StockQuantity = 30,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 5,
                            Description = "Populär skönlitterär roman",
                            Name = "Bestsellerroman",
                            Price = 249m,
                            StockQuantity = 40,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 1,
                            Description = "Högpresterande dator för gaming",
                            Name = "Gaming PC",
                            Price = 18999m,
                            StockQuantity = 5,
                            SupplierId = 6
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 1,
                            Description = "10\" surfplatta med WiFi",
                            Name = "Tablet",
                            Price = 4299m,
                            StockQuantity = 9,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 1,
                            Description = "Portabel högtalare med 20h batteritid",
                            Name = "Bluetooth-högtalare",
                            Price = 899m,
                            StockQuantity = 22,
                            SupplierId = 6
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            Description = "Programmerbar kaffebryggare",
                            Name = "Kaffebryggare",
                            Price = 799m,
                            StockQuantity = 14,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            Description = "Funktionströja för träning",
                            Name = "Träningströja",
                            Price = 499m,
                            StockQuantity = 35,
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            ContactPerson = "Anna Lindberg",
                            Email = "anna@techvision.se",
                            Name = "TechVision AB",
                            Phone = -4620
                        },
                        new
                        {
                            SupplierId = 2,
                            ContactPerson = "Johan Bergman",
                            Email = "johan@homestyle.se",
                            Name = "HomeStyle",
                            Phone = -5839
                        },
                        new
                        {
                            SupplierId = 3,
                            ContactPerson = "Maria Ek",
                            Email = "maria@fashionfirst.se",
                            Name = "Fashion First",
                            Phone = -7058
                        },
                        new
                        {
                            SupplierId = 4,
                            ContactPerson = "Erik Strand",
                            Email = "erik@sportmax.se",
                            Name = "SportMax",
                            Phone = -8274
                        },
                        new
                        {
                            SupplierId = 5,
                            ContactPerson = "Karl Holm",
                            Email = "karl@nordicelec.se",
                            Name = "Nordic Electronics",
                            Phone = -9398
                        },
                        new
                        {
                            SupplierId = 6,
                            ContactPerson = "Lisa Björk",
                            Email = "lisa@globalgadgets.se",
                            Name = "Global Gadgets",
                            Phone = -9617
                        });
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Category", b =>
                {
                    b.HasOne("Labb1___LINQ.Models.Supplier", null)
                        .WithMany("Categories")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Order", b =>
                {
                    b.HasOne("Labb1___LINQ.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb1___LINQ.Models.OrderDetail", b =>
                {
                    b.HasOne("Labb1___LINQ.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1___LINQ.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Product", b =>
                {
                    b.HasOne("Labb1___LINQ.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1___LINQ.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Labb1___LINQ.Models.Supplier", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
